Feature
rpopov94/haker-news pull request #1
Opened 2022-07-29 07:55 UTC by rpopov94

2022-07-29 13:14 UTC, crutch12 commented
Отдал @stilwuc

2022-08-02 15:53 UTC, crutch12 commented
@stilwuc не забудь про PR

2022-08-03 12:56 UTC, Stilwuc requested changes
В целом солидно. Структура хорошая, типизация на месте, функционально норм.
Пару вещей поправь только)

2022-08-03 12:56 UTC, Stilwuc commented on package.json
> +    "typescript": "^4.7.4",
Лучше разделять devDeps и не dev.
В SPA по факту пофиг, так как все нужные зависимости забандлятся а не нужные нет.
В SSR уже более критично, если в прод сборку будут попадать typescript всякие.
Но и для чтения тоже более удобно когда они разделены.
(Более совет на будущее, и править необязательно)

2022-08-03 12:56 UTC, Stilwuc commented on src/App.tsx
> +import Loader from "./components/loader/Loader";
Тут двойные ковычки, а выше ординарные.
В этом же файле на 13 строке `;` потерял)
Советую чтобы не парится над форматированием законектить prettier и проходится им либо на autoSave либо перед коммитом

2022-08-03 12:56 UTC, Stilwuc commented on src/App.tsx
> +const App = () => {
Закинь еще ПР на `codesandbox` после исправлений

2022-08-03 12:56 UTC, Stilwuc commented on src/components/home/Home.tsx
> +        setInterval(() =>{
Хорошей практикой считается удаление интервала которого ты создал на unmount компонента.
А то уйдешь ты с этой страницы, а interval останется в фоне и будет выполняться, и так можно нормально потушить операту или сделать непонятное поведения со стейтом

2022-08-03 12:56 UTC, Stilwuc commented on src/components/home/Home.tsx
> +    }, [])
Я так понимаю useEffect два раза выполняется, и из-за этого 2 раза refresh тригерится. При clearInterval должно починится
![image](https://user-images.githubusercontent.com/44724024/182604383-57c1043d-6cf4-4eb1-af4b-cf7192f21de9.png)

2022-08-03 12:56 UTC, Stilwuc commented on src/components/home/Home.tsx
> +                        <li>
key для элементов массива не забывай делать. Важная штука которая нужна для оптимизации списков
https://reactjs.org/docs/lists-and-keys.html#keys

2022-08-03 12:56 UTC, Stilwuc commented on src/components/header/Header.tsx
> +  const updateNews = () => {
Очень странно себя ведет при нажатии. Начинает дублировать итемы, скорей всего опять из-за двойного useEffect (если что вот ссылочка пр него https://javascript.plainenglish.io/react-18-useeffect-double-call-for-apis-emergency-fix-724b7ee6a646)
![chrome-capture-2022-7-3](https://user-images.githubusercontent.com/44724024/182605639-d1d6a220-6878-4650-b3cf-9aec12505df6.gif)

2022-08-03 12:56 UTC, Stilwuc commented on src/types/actions.ts
> +interface loadNewsAction {
интерфейсы и типы обычно пишем в `PascalCase`, для различия между обычными переменными

2022-08-03 12:56 UTC, Stilwuc commented on src/components/new_id/CommentsList.tsx
> +    const arrayOfComments = (Array.isArray(comments) && comments) || comments?.comments;
Что-то condition не робит
Ссылка на новость http://localhost:3000/news/32330043
![image](https://user-images.githubusercontent.com/44724024/182606912-e8000251-6745-4422-9cf6-eeba62df8b87.png)
![image](https://user-images.githubusercontent.com/44724024/182606882-10fe58a5-f1e3-4b74-83fa-2a0d89c5dc2c.png)

2022-08-03 12:56 UTC, Stilwuc commented on src/components/new_id/NewID.tsx
> +                                <div className="color">
Ошибки в консоли поглядывай, в `<p>` вставлять `<div>` в валидной верстке нельзя
![image](https://user-images.githubusercontent.com/44724024/182607241-e4111931-2e7d-4d79-8471-57ef68eb5513.png)

2022-08-03 12:56 UTC, Stilwuc commented on src/components/new_id/NewID.tsx
> +import './style.css';
Лучше хотя бы модульный css делать, а то сейчас глобал скоуп стилей.
Ну а еще лучше `styled-components`

2022-08-03 12:56 UTC, Stilwuc commented on src/types/types.ts
> +    comments: Array<CommentsItemType>;
Лучше сокращенный вариант типизации массивом юзать, читать легче
```suggestion
    comments: CommentsItemType[];
```

2022-08-03 12:56 UTC, Stilwuc commented on src/components/header/Header.tsx
> +
Функция обманка получается)

2022-08-03 12:56 UTC, Stilwuc commented on src/components/new_id/CommentsList.tsx
> +            {item?.user}<br/>
по типизации аргумента выше, у тебя статичный тип `CommentsItemType` и он не может быть undefined, либо лишние `?` либо типизация аргумента неверная

2022-08-03 12:56 UTC, Stilwuc commented on src/components/new_id/CommentsList.tsx
> +            {getDate(Number(item?.time))}<br/>
Лучше не юзать `<br />`
Обычно оборачиваем в `<div />` и стилями решаем

2022-08-03 12:56 UTC, Stilwuc commented on src/store/action-creators/manageApi.ts
> +            }, 200)
Интересно, а зачем setTimeout?)
Выглядит как костыль просто

2022-08-03 12:56 UTC, Stilwuc commented on src/store/action-creators/manageApi.ts
> +                    .then((responses) => Promise.all(responses.map((response) => response.clone().json())))
Внутренний `Promise,all` не нужен

2022-08-03 12:56 UTC, Stilwuc commented on src/store/index.ts
> +export const store = createStore(rootReducer, applyMiddleware(thunk))
Одинаковые файлы
![image](https://user-images.githubusercontent.com/44724024/182613072-ced55153-7b27-49c1-8ab3-f5ccbf285067.png)

2022-08-04 09:03 UTC, rpopov94 commented on src/components/header/Header.tsx
> +  const updateNews = () => {
не знаю как это сделать

2022-08-04 09:07 UTC, Stilwuc commented on src/components/header/Header.tsx
> +  const updateNews = () => {
Самое простое, заюзай какой нибудь fetch менеджер. npm `swr` или `reqct-query`. Они будут  контролировать лишние запросы когда данные уже есть.
Ну или всегда можно сделать чтобы fetchNews не добавлял новости в массив, а заменял полностью

2022-08-04 12:15 UTC, rpopov94 commented on src/store/action-creators/manageApi.ts
> +                    .then((responses) => Promise.all(responses.map((response) => response.clone().json())))
Я делал это по учебнику

2022-08-04 13:07 UTC, rpopov94 commented on src/App.tsx
> +const App = () => {
Сделал, только не могу там на feature переключиться

2022-08-04 13:18 UTC, Stilwuc commented on src/App.tsx
> +const App = () => {
Хм, странно, там по идее вот тут должно быть доступен свитч ветки
![image](https://user-images.githubusercontent.com/44724024/182856784-2245c7c0-4884-47b6-8261-8255ede0f6a7.png)

2022-08-04 13:37 UTC, rpopov94 commented on src/App.tsx
> +const App = () => {
https://codesandbox.io/s/great-solomon-imc898

2022-08-04 13:48 UTC, Stilwuc commented on src/App.tsx
> +const App = () => {
https://codesandbox.io/s/github/rpopov94/haker-news/tree/feature/

2022-08-05 07:45 UTC, rpopov94 commented
Всё поправил

2022-08-05 08:21 UTC, Stilwuc requested changes
Еще пару вещей нашел)

2022-08-05 08:21 UTC, Stilwuc commented on package.json
> +    "@types/REACT-REDUX": "npm:@types/react-redux@^7.1.24",
Забыл в тот раз написать, а зачем этот package alias?)

2022-08-05 08:21 UTC, Stilwuc commented on src/components/new_id/NewID.tsx
> +    const newsItems = useTypedSelector(state => state.news);
Не самая лучшая реализация получения инфы о выбранной новости.
Так как если запрос на получения всех новостей не было, то и новость в url не отобразится
Вот например я `F5` нажал
![image](https://user-images.githubusercontent.com/44724024/183032678-cc45bb07-9707-4802-a053-807388dc3a4a.png)

2022-08-05 08:21 UTC, Stilwuc commented on src/utils/utils.ts
> +    return `${t.getUTCDay() + 1}/${t.getMonth()}/${t.getFullYear()}`
Что-то кстати либо новости не новые, либо дата неправильно выводится
![image](https://user-images.githubusercontent.com/44724024/183033877-150f5342-15f3-44d0-acbb-44f420478be4.png)

2022-08-05 08:21 UTC, Stilwuc commented on src/store/reducers/news_reducer.ts
> +                        else return Number(null);
А почему Number(null) а не просто 0?)

2022-08-05 08:21 UTC, Stilwuc commented on src/components/new_id/CommentsList.tsx
> +        {arrayOfComments.map((item: CommentsItemType, id) =>{
Комменты не отображаются по ощущениям.
Вот новость
![image](https://user-images.githubusercontent.com/44724024/183034343-42de8320-d9d2-4dcd-99cf-822fe883bb15.png)
Вот как она выглядит в оригинале
![image](https://user-images.githubusercontent.com/44724024/183034388-9442c6bd-644e-479b-8854-68211caa9221.png)

2022-08-05 08:21 UTC, Stilwuc commented on src/components/new_id/NewID.tsx
> +        () => newsItems.news.find((item: NewsItemType) => item.id === Number(id)),
приведения к числу через класс `Number` допустимо, но если что советую более легкий вариант 
Читать легче
```suggestion
        () => newsItems.news.find((item: NewsItemType) => item.id === +id),
```

2022-08-05 08:21 UTC, Stilwuc commented on src/App.tsx
> +        <Route path="/news" element={
Зачем еще один роут дублирующий `/`, просто редиректи на `/`

2022-08-05 17:02 UTC, rpopov94 commented on package.json
> +    "@types/REACT-REDUX": "npm:@types/react-redux@^7.1.24",
В принципе никчему, не пригодились

2022-08-05 17:05 UTC, rpopov94 commented on src/components/new_id/CommentsList.tsx
> +        {arrayOfComments.map((item: CommentsItemType, id) =>{
Я вообще этот компонент обернул в Error Boundary + Suspense, ошибок вроде не возвращает. Не понимаю почему не работает.

2022-08-05 18:58 UTC, Stilwuc commented on src/components/new_id/CommentsList.tsx
> +        {arrayOfComments.map((item: CommentsItemType, id) =>{
Ну, тут все просто на самом деле, вот запрос который уходит о получении информации о новости
Приходит определенный объект с ключом `comments`. Соответсвенно тебе надо брать все комменты оттуда
![image](https://user-images.githubusercontent.com/44724024/183143487-51a4be3d-4f2c-4bbf-ac47-ebb98fb215a9.png)

2022-08-06 14:35 UTC, rpopov94 commented
Что смог поправил

2022-08-06 15:34 UTC, rpopov94 commented on src/components/new_id/NewID.tsx
> +    const newsItems = useTypedSelector(state => state.news);
Не понимаю почему при условии, что вся информация из запроса отображается, переменные выкрашиваются красным цветом и вылазит ошибка что такого поля нет

2022-08-06 18:16 UTC, Stilwuc commented
Нормас нормас 👍 
@rpopov94 Можешь мержить

2022-08-09 11:40 UTC, merged